spring.application.name=easytime_java

# conexion a la base de datos

spring.datasource.url=jdbc:mysql://localhost:3306/bd_easytime
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# usuario por defecto 

spring.security.user.name=admin
spring.security.user.password=1234
